---
title: "Benchmark_GrabowskiLaughlinBIO247Project"
author: "Ty"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```


##Honeybees 2014
```{r}
#Load in data
hb2014 <- read.csv("EB_visitation_honeybees_2014.csv")

#Remove unnecessary columns to only have number of visitations per species columns remaining
hb2014 <- subset(hb2014, select = -c(1:3))

# placeholder for total number of visitation
sumhb2014 <- c()

for(each in hb2014) {
  sumhb2014 <- append(sumhb2014, sum(each))
}

#Get column names
namehb2014 <- c()

#Creates a vector containing the column names from the original data file
for(each in hb2014) {
  namehb2014 <- colnames(hb2014, do.NULL = FALSE)
}


#Clean column names to only have genus and species

#Creates vector to store each of the genera
genushb2014 <- c()

for (each in namehb2014) {
  #Stores each Genus at a time after removing other unwanted name components
  tempgenus <- unlist(strsplit(each, "\\."))[1]
  #this creates a vector with the row numbers of each genus
  rowNumbers <- which(each == namehb2014)
  #Using the indexing of rownumbers, each genus is added to genushb2014 in the proper order
  genushb2014[rowNumbers] <- tempgenus
}

#Creates vector to store each of the epithets
epithethb2014 <- c()

for (each in namehb2014) {
  #Stores each epithet at a time after removing other unwanted name components
  tempepithet <- unlist(strsplit(each, "\\."))[2]
  #this creates a vector with the row numbers of each epithet
  rowNumbers <- which(each == namehb2014)
  #Using the indexing of rownumbers, each epithet is added to epithethb2014 in the proper order
  epithethb2014[rowNumbers] <- tempepithet
}

#Combine genus and species for each flower into 1 data point per flower
scientificNamehb2014 <- paste(genushb2014, epithethb2014)

#Creates the dataframe that will be used to plot the means, with the means in one column and the Scientific names in the other
plotDatahb2014 <- data.frame(
  Number_of_Visits = sumhb2014,
  ScientificNames = scientificNamehb2014
)

#Arbitrarily removes low number of visitations from the data
plotDatahb2014 <- subset(plotDatahb2014, Number_of_Visits>130)

#Attempt at new version of plotting
ggplot(plotDatahb2014, aes(x= reorder(ScientificNames, -Number_of_Visits, FUN = sum), y= Number_of_Visits)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) +
  geom_text(aes(x=1, y=12000, label="Stretch it"), vjust=-1) +
  theme(axis.text.x = element_text(angle = 45, size = 9,color = "black", face = "plain", vjust = 1, hjust = 1),plot.margin = margin(10, 10, 10, 10)) + 
  xlab("Scientific name") +
  ylab("Number of visits")  

```
