---
title: "R Day 4 Exercise 1"
author: "Ty"
date: '2022-09-20'
output: html_document
---


This sets up th various color options for shirt, with hashtags in front of all but one color options at a time.
```{r}
#shirt <- "red"
#shirt <- "blue"
shirt <- "yellow"
#shirt <- "green"
```


This gives an example of how to use and set up if/else statements in r
```{r}
if (shirt == "red") {
  print("eat eggs")
} else if (shirt == "yellow") {
  print("eat banana")
} else if (shirt == "green") {
  print("eat broccoli")
} else if (shirt == "blue") {
  print("eat blueberries")
} else {
  print("eat yogurt")
}
```

This selects one random number between 1 and 1000
```{r}
stop <- sample (1:1000, 1)
```

This gives an example of a while loop, which runs until it reaches the random number that was previously selected
```{r}
num = 0
while (num < stop){
  stop <- sample (1:1000, 1)
}

print("Pop goes the weasel")
```




























